services:
  assistant:
    build: .
    volumes:
      - .:/AI-Assistant:rw
      - static:/static
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: gunicorn -w 4 --bind 0.0.0.0:$FLASK_PORT --timeout 180 --log-level debug run:app
    restart: always
    depends_on:
      - qdrant
      - redis
      - mongodb
    environment:
      - .env

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - vectordata:/qdrant/storage

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6378:6379"

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db

volumes:
  vectordata:
  static:
  mongodb_data:
