services:
  assistant:
    build: .
    volumes:
      - .:/AI-Assistant:rw
      - static:/static
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: gunicorn -w 4 --bind 0.0.0.0:$FLASK_PORT --timeout 600 --log-level debug run:app
    restart: always
    depends_on:
      - qdrant
      - redis
      - mongodb
      - neo4j
    environment:
      - .env

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - vectordata:/qdrant/storage

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6378:6379"

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db

  neo4j:
    image: neo4j:5.15
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    restart: always

volumes:
  vectordata:
  static:
  mongodb_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
