[tool.poetry]
name = "ai-assistant"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
Flask = "^3.0.3"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
openai = "^1.51.0"
PyYAML = "^6.0.2"
pandas = "^2.2.3"
neo4j = "^4.4"
biocypher = "^0.6.1"
scikit-learn = "^1.5.2"
qdrant-client = "^1.12.0"
tiktoken = "^0.8.0"
google-generativeai = "^0.8.3"
pyjwt = "^2.10.0"
flask-limiter = "^3.8.0"
gunicorn = "^23.0.0"
pypdf2 = "^3.0.1"
pytest = "^8.3.4"
flask-cors = "^5.0.0"
sqlalchemy = "^2.0.41"
redis = "^6.2.0"
flask-socketio = "^5.5.1"
eventlet = "^0.40.1"
websocket-client = "^1.8.0"
langgraph = "^0.5.0"
sentence-transformers = "^4.1.0"
pymupdf = "^1.26.1"
pymupdf4llm = "^0.0.25"
langchain = "^0.1.9"
langchain-text-splitters = "^0.0.1"
pyt2s = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
